### ISSUE TITLE
keeps closeing after the main menu 

### ISSUE THREAD

**Issue by FlorianGrille** [uzair-ashraf/vrc-owo-suit#9]
the programm after i started open to the menu and closes after 1 second , did i need to install a software for it or some runtime 
manly the last version bugges out the older beta one start up  but not works anymore during updates

**Comment by FlorianGrille** [comment]
now i get this
 Exception occurred during processing of request from ('127.0.0.1', 58692)
Traceback (most recent call last):
  File "socketserver.py", line 683, in process_request_thread
  File "socketserver.py", line 360, in finish_request
  File "socketserver.py", line 747, in __init__
  File "pythonosc\osc_server.py", line 29, in handle
  File "pythonosc\dispatcher.py", line 194, in call_handlers_for_packet
  File "pythonosc\dispatcher.py", line 57, in invoke
  File "owo_suit.py", line 85, in on_collission_enter
KeyError: <OWOGame.Muscle object at 0x000002595B665F80>
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 58692)
Traceback (most recent call last):
  File "socketserver.py", line 683, in process_request_thread
  File "socketserver.py", line 360, in finish_request
  File "socketserver.py", line 747, in __init__
  File "pythonosc\osc_server.py", line 29, in handle
  File "pythonosc\dispatcher.py", line 194, in call_handlers_for_packet
  File "pythonosc\dispatcher.py", line 57, in invoke
  File "owo_suit.py", line 85, in on_collission_enter
KeyError: <OWOGame.Muscle object at 0x000002595A7B3480>

**Comment by FlorianGrille** [comment]
i cant feel anything

**Comment by FlorianGrille** [comment]
it keeps disconecting

**Comment by EinDev** [comment]
Hi, i just wanted to know wether this is still an issue? Can you confirm that it is still broken on the newest release?
